[package]
name = "fervid"
description = "Vue SFC compiler written in Rust"
version = "0.0.1"
edition = "2021"
authors = ["Marsel Shaikhin <phoenix.apps@yahoo.com>"]
repository = "https://github.com/phoenix-ru/rust-vue-compiler"
license = "Apache-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nom = "7"
regex = "1"
phf = { version = "0.11", features = ["macros"] }
swc_common = "0.29.17"
swc_ecma_codegen = "0.128.*"
swc_ecma_parser = "0.123.2"
swc_core = { version = "0.44.*", features = ["plugin_transform"] }

[dev-dependencies]
criterion = "0.3"

[[bench]]
name = "parser_bench"
harness = false

[[bench]]
name = "codegen_bench"
harness = false
